apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-vozb
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0028-tenant/tkrw-pr712-0075-0028-app/devfile-sample-vozb@sha256:8dd5e9a54f95b3bc3488b9583b57db6ab4bbfb391fda3c9444b3caae48ed2f0b
        name: my-nodejs
        resources: {}
status: {}
